var product = [
  {
    id: "SP1",
    name: "Casio AE-1200WHD-1AVDF Nam Quartz ",
    img: "watch1.jpg",
    price: 335600,
    detail: {
      warrantee: "quốc tế 2 năm ",
      color: "trắng",
      resistance: "3 ATM(30m)",
      DangMatso: "vuông",
      LoaiDay: "Dây Inox(thép không gỉ)",
      LoaiKinh: "Mineral Crystal (Kính Cứng)",
      LoaiPin: "Pin (Quartz)",
      SizeMatSo: "45mm",
      Hang: "Casio",
    },

    type: 1,
  },
  {
    id: "SP2",
    name: "Casio MTP-1374L-1AVDF Nam Quartz",
    img: "watch2.jpg",
    price: 400000,
    detail: {
      warrantee: "quốc tế 2 năm ",
      color: "trắng",
      resistance: "3 ATM(30m)",
      DangMatso: "vuông",
      LoaiDay: "Dây Inox(thép không gỉ)",
      LoaiKinh: "Mineral Crystal (Kính Cứng)",
      LoaiPin: "Pin (Quartz)",
      SizeMatSo: "45mm",
      Hang: "Casio",
    },
    type: 1,
  },
  {
    id: "SP3",
    name: "Casio MTP-1374D-1AVDF Nam Quartz",
    img: "watch3.jpg",
    price: 350000,
    detail: {
      warrantee: "quốc tế 2 năm ",
      color: "trắng",
      resistance: "3 ATM(30m)",
      DangMatso: "vuông",
      LoaiDay: "Dây Inox(thép không gỉ)",
      LoaiKinh: "Mineral Crystal (Kính Cứng)",
      LoaiPin: "Pin (Quartz)",
      SizeMatSo: "45mm",
      Hang: "Casio",
    },
    type: 1,
  },
  {
    id: "SP4",
    name: "Casio B640WC-5ADF Nữ Quartz",
    img: "watch4.jpg",
    price: 564000,
    detail: {
      warrantee: "quốc tế 2 năm ",
      color: "trắng",
      resistance: "3 ATM(30m)",
      DangMatso: "vuông",
      LoaiDay: "Dây Inox(thép không gỉ)",
      LoaiKinh: "Mineral Crystal (Kính Cứng)",
      LoaiPin: "Pin (Quartz)",
      SizeMatSo: "45mm",
      Hang: "Casio",
    },
    type: 1,
  },

  {
    id: "SP5",
    name: "Casio B640WC-5ADF Nữ Quartz",
    img: "orient1.jpg",
    price: 564000,
    detail: {
      warrantee: "quốc tế 2 năm ",
      color: "trắng",
      resistance: "3 ATM(30m)",
      DangMatso: "vuông",
      LoaiDay: "Dây Inox(thép không gỉ)",
      LoaiKinh: "Mineral Crystal (Kính Cứng)",
      LoaiPin: "Pin (Quartz)",
      SizeMatSo: "45mm",
      Hang: "Casio",
    },
    type: 2,
  },

  {
    id: "SP6",
    name: "Casio B640WC-5ADF Nữ Quartz",
    img: "orient2.jpg",
    price: 564000,
    detail: {
      warrantee: "quốc tế 2 năm ",
      color: "trắng",
      resistance: "3 ATM(30m)",
      DangMatso: "vuông",
      LoaiDay: "Dây Inox(thép không gỉ)",
      LoaiKinh: "Mineral Crystal (Kính Cứng)",
      LoaiPin: "Pin (Quartz)",
      SizeMatSo: "45mm",
      Hang: "Casio",
    },
    type: 2,
  },

  {
    id: "SP7",
    name: "Casio B640WC-5ADF Nữ Quartz",
    img: "orient3.jpg",
    price: 564000,
    detail: {
      warrantee: "quốc tế 2 năm ",
      color: "trắng",
      resistance: "3 ATM(30m)",
      DangMatso: "vuông",
      LoaiDay: "Dây Inox(thép không gỉ)",
      LoaiKinh: "Mineral Crystal (Kính Cứng)",
      LoaiPin: "Pin (Quartz)",
      SizeMatSo: "45mm",
      Hang: "Casio",
    },
    type: 2,
  },

  {
    id: "SP8",
    name: "Casio B640WC-5ADF Nữ Quartz",
    img: "orient4.jpg",
    price: 564000,
    detail: {
      warrantee: "quốc tế 2 năm ",
      color: "trắng",
      resistance: "3 ATM(30m)",
      DangMatso: "vuông",
      LoaiDay: "Dây Inox(thép không gỉ)",
      LoaiKinh: "Mineral Crystal (Kính Cứng)",
      LoaiPin: "Pin (Quartz)",
      SizeMatSo: "45mm",
      Hang: "Casio",
    },
    type: 2,
  },

  {
    id: "SP9",
    name: "Casio B640WC-5ADF Nữ Quartz",
    img: "tissot1.jpg",
    price: 564000,
    detail: {
      warrantee: "quốc tế 2 năm ",
      color: "trắng",
      resistance: "3 ATM(30m)",
      DangMatso: "vuông",
      LoaiDay: "Dây Inox(thép không gỉ)",
      LoaiKinh: "Mineral Crystal (Kính Cứng)",
      LoaiPin: "Pin (Quartz)",
      SizeMatSo: "45mm",
      Hang: "Casio",
    },
    type: 3,
  },

  {
    id: "SP10",
    name: "Casio B640WC-5ADF Nữ Quartz",
    img: "tissot2.jpg",
    price: 564000,
    detail: {
      warrantee: "quốc tế 2 năm ",
      color: "trắng",
      resistance: "3 ATM(30m)",
      DangMatso: "vuông",
      LoaiDay: "Dây Inox(thép không gỉ)",
      LoaiKinh: "Mineral Crystal (Kính Cứng)",
      LoaiPin: "Pin (Quartz)",
      SizeMatSo: "45mm",
      Hang: "Casio",
    },
    type: 3,
  },

  {
    id: "SP11",
    name: "Casio B640WC-5ADF Nữ Quartz",
    img: "tissot3.jpg",
    price: 564000,
    detail: {
      warrantee: "quốc tế 2 năm ",
      color: "trắng",
      resistance: "3 ATM(30m)",
      DangMatso: "vuông",
      LoaiDay: "Dây Inox(thép không gỉ)",
      LoaiKinh: "Mineral Crystal (Kính Cứng)",
      LoaiPin: "Pin (Quartz)",
      SizeMatSo: "45mm",
      Hang: "Casio",
    },
    type: 3,
  },

  {
    id: "SP12",
    name: "Casio B640WC-5ADF Nữ Quartz",
    img: "tissot7.jpg",
    price: 564000,
    detail: {
      warrantee: "quốc tế 2 năm ",
      color: "trắng",
      resistance: "3 ATM(30m)",
      DangMatso: "vuông",
      LoaiDay: "Dây Inox(thép không gỉ)",
      LoaiKinh: "Mineral Crystal (Kính Cứng)",
      LoaiPin: "Pin (Quartz)",
      SizeMatSo: "45mm",
      Hang: "Casio",
    },
    type: 3,
  },
];